DROP TABLE BOARD;

CREATE TABLE BOARD(
    NUM NUMBER(4) PRIMARY KEY,
    AUTHOR VARCHAR2(20),
    TITLE VARCHAR2(50),
    CONTENT VARCHAR2(100),
    WRITEDAY DATE DEFAULT SYSDATE,
    READCNT NUMBER(4) DEFAULT 0,
    REPROOT NUMBER(4),
    REPSTEP NUMBER(4),
    REPINDENT NUMBER(4)
);

DROP SEQUENCE BOARD_SEQ;

CREATE SEQUENCE BOARD_SEQ;

INSERT INTO BOARD (
    NUM,
    AUTHOR,
    TITLE,
    CONTENT,
    REPROOT,
    REPSTEP,
    REPINDENT
) VALUES (
    BOARD_SEQ.NEXTVAL,
    '홍길동',
    '테스트',
    '테스트입니다',
    BOARD_SEQ.CURRVAL,
    0,
    0
);

COMMIT;